[package]
name = "gcl"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "GCL"
path = "src/main.rs"

[dependencies]
windows-reactor = "0.100"

[build-dependencies]
embed-resource = "3"
windows-reactor-setup = "0.100"

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
