name: Build GCL

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: ["x86_64-pc-windows-msvc", "aarch64-pc-windows-msvc"]

    steps:
      - uses: actions/checkout@v7
      - name: Build
        run: cargo build --target ${{ matrix.target }} --verbose
